### ISSUE TITLE
Reviewer system changed from L1-L2 to Internal-External.

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-review-webapp#19]
Associated changes: 
L1 L2 tags are relabelled as Internal Reviewer and External Reviewer @ricardomiron is this to be done in this way?
The application flow is such: 
> App enters pipeline 
> Internal reviewer has 7 days to review it. He can: 
                  (a) Pass it (becomes a DPG)
                  (b) Fail it (becomes ineligible)
                  (c) Ask for consultation (goes to expert panel)
                  (d) Ask for clarification (goes to external reviewer) 
> If it goes for consultation, expert has 7 days to submit his inputs as a note and submit it to external reviewer 
> External reviewer has 2 weeks to ask users for clarifications and get answers. If expert gets answers, he can: 
                  (a) Pass it (becomes a DPG)
                  (b) Fail it (becomes ineligible)
If he doesn’t get answers, after two weeks the DPG is marked as ‘Lapsed’.

**Comment by ricardomiron** [comment]
@PelinSmines this changes fundamentally how the review process works and would need to be discussed, for now, I don't think we should focus on this type of change without.
