### ISSUE TITLE
Reviewer Panel Updates

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-review-webapp#20]
@ricardomiron is it still needed?

Formatting of text received back from experts on reviewers panel to show URLs and spacing

**Comment by ricardomiron** [comment]
@PelinSmines URLs and spacing are working okay, overall text formatting could be improved with the system-wide change to have a proper formatting option but it is not a priority in this section. Closing this for now.

This is how inputs are displayed:
![image](https://github.com/DPGAlliance/publicgoods-review-webapp/assets/18178248/fbf7a308-8211-47c5-848b-7b5869e69bc8)
