### ISSUE TITLE
5 admin panel updates

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-review-webapp#23]
@ricardomiron which of these are still valid?

1 Dashboard changes: 
Removal of big graph
Removal of nominee system 

2. As of now there is only sort option, a filter option should also be there 

3. There should be multi-select options for the sort and filter. For eg: if i want to search for all the Renewal apps that have become DPGs i should be able to. 

4. Ability to search for apps using SDG selected in webapp 

5. The late application details should also list the name of the person the app is under and the date it has been late since.

**Comment by ricardomiron** [comment]
@PelinSmines I think the admin dashboard needs to be completely rethought, let's close this issue for now and delineate the concrete needs.
