### ISSUE TITLE
Enhancement of application form

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-review-webapp#24]
2 links under each question of the form - [Inclusions - Reviewer Guide](https://docs.google.com/spreadsheets/d/1BhuINlx-Wkub0_-doj7LKirV3uMMYEnTxvzMFHHeGb8/edit?usp=sharing)
@ricardomiron can you elaborate on this?

**Comment by ricardomiron** [comment]
@PelinSmines This relates to the idea of integrating more cues and links to the Help Center (now the DPG Wiki) in the application form to help guide users while filling the form, but this should be revisited with the new data structure of how information should be collected and where do we want to add additional cue vs link external resources.
