### ISSUE TITLE
[BUG] API outputs incorrect and inconsistent data

### ISSUE THREAD

**Issue by ricardomiron** [DPGAlliance/publicgoods-review-webapp#36]
The `openLicenseEvidenceURLs` field is outputting incorrect data and not properly retrieving the URL related to that field.

![Image](https://github.com/DPGAlliance/publicgoods-review-webapp/assets/18178248/3f818624-545c-461e-9214-9d5d92f383d5)

**Comment by law909** [comment]
The cause of this bug could have triggered many other data errors in API outputs as well.
